### ISSUE TITLE
Small addition for your great howto

### ISSUE THREAD

**Issue by dreimer1986** [Flodu31/HomeAssistant-PeugeotIntegration#1]
Hey at first thanks for the great howto. My first try caused 4 calls to the server on every refresh and now you showed that it works fine with just one. 

I upgraded to your solution as my e-208 has some identity crisis and thinks it's a hybrid car now. (I still think this happened after I registered the TELEMAINTENANCE service in Android app) I opened a longer bug report on flobz' server solution github regarding that and he recommended your way to go while we were discussing my problems and my way to use his server. Now that things are fixed I merged my stuff into your solution. Maybe you have some use for it, especially the working device_tracker.

https://community.home-assistant.io/t/peugeot-citroen-ds-cars-connected-car/202949/21

**Comment by Flodu31** [comment]
Cool, thanks for the update.
I'll have a look next week :)
