### ISSUE TITLE
All sensors unavailable after restoring HA backup

### ISSUE THREAD

**Issue by Cassiopea1** [Flodu31/HomeAssistant-PeugeotIntegration#10]
After restoring an 1 hour old backup all the car sensors configured in `configuration.yaml` went unavailable and the PSA Car Controller web ui does not react.
It is supposed to be like this? There is something to be done in such a case?

**Comment by DavidFFerreira** [comment]
check you errors at Addon Log

**Comment by DavidFFerreira** [comment]
@Cassiopea1 did you solve that? since friday, all my sensors are unavailable

**Comment by Flodu31** [comment]
The problem is for me with the last version, 2.5.1. I have some errors with this version, updates are not like other times and so on.

**Comment by DavidFFerreira** [comment]
@Flodu31  found the probleme. He did change the name of the method =/
You can't use **get_vehicleinfo** anymore, now is **get_vehicle_info** , but still no luck, problably they did more changes and didnt care about other addons
![image](https://user-images.githubusercontent.com/32928749/134894339-e5b438c4-214f-4c39-84e2-d36fba5ba40d.png)

**Comment by Flodu31** [comment]
Thanks for the check. @flobz can you have a look?

Thanks again both for your help.
Florent

**Comment by flobz** [comment]
The endpoint didn't change. Method name and endpoint aren't related. You need to look at the line just below method name.

**Comment by dreimer1986** [comment]
Did the internal 172.x.x.x IP of the addin container change? I switched to enable the port forwarding off of the container and then used the static ip of my home assistant instance to finally bypass this hassle:
![image](https://user-images.githubusercontent.com/29841368/135037918-617019ca-9bb4-4172-b2f1-7103a4e16bd8.png)
