### ISSUE TITLE
Controlling the climate its possible? getting temperature inside the car?! Citroen e-C4

### ISSUE THREAD

**Issue by DavidFFerreira** [Flodu31/HomeAssistant-PeugeotIntegration#11]
Controlling the climate its possible? getting temperature inside the car?!

**Comment by DavidFFerreira** [comment]
nice, closed without answer. Congrats, nice repo =)

**Comment by dreimer1986** [comment]
It was likely closed bacause you report in the wrong one. Just read the readme and you know that https://github.com/flobz/psa_car_controller is the way to go.

**Comment by DavidFFerreira** [comment]
@dreimer1986 unfortunally neither there anyone answer queries for HA

**Comment by dreimer1986** [comment]
Well, it's no HA question, it's a API question. So in theory it still belongs there IMO...
