### ISSUE TITLE
Intégration Officielle ?

### ISSUE THREAD

**Issue by landaisbenj** [Flodu31/HomeAssistant-PeugeotIntegration#14]
Salut. Tout d'abord merci pour le travail. Cela fait un an que j'ai la e-208, et je m'etais toujours dis qu'il faudrait une integration à HA. Je viens tous juste de tombé par hasard sur votre travail, ca bluffé !!! 

Du coup je vais tester l'intégration via les add-on de HA, mais le site d'où provenait la source (forum automobile propre), parlait d'un id et d'un code client. J'avais déjà regardé l'api PSA, et je m'étais toujours demandé pourquoi il n'y avait pas d'intégration officielle sur HA...

Bref pour le contexte. Du coup je me demande, pourquoi ne pas faire créer un compte dev à chaque utilisateur comme il est fait avec l'intégration TUYA, ou d'autre (comme ca, chacun a son propre id et code client) ? Et du coup pourquoi ne pas créer une integration officielle, ou au moins via HACS ?

En tout cas merci pour le job, je vais pouvoir tester tout ca.

**Comment by landaisbenj** [comment]
Bon du coup j'ai un premier probleme. J'ai intégré l'add, installé (en passant je ne sais pas ce qu'il faut faire avec la configuration...), j'ai reussi à le lancer, entrer mon compte et me connecté, puis ensuite il me change d'onglet pour demander un SMS avec un code et rentrer mon pin. J'ai supposé qu'il s'agissait du PIN de la voiture (celui que l'application officielle me demande lourdement constemment...) et quand je l'ai fais, j'ai eu un bref message de certificat SSL, puis j'ai été switché sur les onglets d'utilisation sans que rien ne s'affiche. Du coup je ne peux plus retourner dans le menu config non plus...

**Comment by flobz** [comment]
https://github.com/flobz/psa_car_controller/issues/260

**Comment by landaisbenj** [comment]
Yes thanks i see this when i navigate between all repo. I continue my search

**Comment by flobz** [comment]
Your search?

**Comment by landaisbenj** [comment]
Yes to review all information to know between this repo, the ha add-on repo, et your main psa car controller repo :) How to solve my bug, and answer another question like what is wakeup switch ..

**Comment by flobz** [comment]
Official integration could be very interesting I agree.
