### ISSUE TITLE
SMS code issue

### ISSUE THREAD

**Issue by markjsmith** [Flodu31/HomeAssistant-PeugeotIntegration#16]
Hi,
I may be missing something, but when I try to log in using a MyVauxhall account, it appears to work but I never get an SMS message, and do not have a pin on my app and no way of adding one. Or should I be registering on a PSA app?

**Comment by dreimer1986** [comment]
Here you report as this is the Addin you have problems with. https://github.com/flobz/psa_car_controller
This repo ONLY explains how to get the values of it into HA. And one thing first. If you did not register to the My Peugeot App, you cannot use this addin at all.

**Comment by markjsmith** [comment]
Very true! Since pair3d with the car and all works great. I’ll work through your notes here now. Many thanks
