### ISSUE TITLE
everything working in addon but no weppage te get enitties

### ISSUE THREAD

**Issue by jeroenvdd** [Flodu31/HomeAssistant-PeugeotIntegration#18]
Hi!
I've got a small question everything seems to be working on my home assistant addon,
but when I visit:
http://192.168.0.140:5000/get_vehicleinfo/thecarvin?from_cache=1

I don't see a web page so I don't know where to get the entity names etc,
any idea?

**Comment by Flodu31** [comment]
Hello,
I have no problem to access this webpage on my side.
Did you enable the web interface? 

![image](https://user-images.githubusercontent.com/15648175/152507189-5302b780-0acc-4205-b409-d34d02fd846c.png)

Florent

**Comment by azcn2503** [comment]
I'm experiencing the same thing. I cannot access the web interface on port 5000 when browsing to `http://my-home-assistant-ip-address:5000` but the interface does load via Ingress in the Home Assistant UI.

**Comment by Flodu31** [comment]
Same answer, did you enabled the web interface?

**Comment by azcn2503** [comment]
It is working now when I set the Host field to 5000 :+1:

**Comment by jeroenvdd** [comment]
maybe change te word host to port?

**Comment by Flodu31** [comment]
You are in the wrong repo for that: https://github.com/flobz/psa_car_controller

**Comment by jove01** [comment]
Hello
I also can't access the webpage
<img width="755" alt="image" src="https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/assets/116289742/2392a5c6-734b-4546-b6da-a39d453e8b25">
I think, 5000 is activated.
Thanks

**Comment by Flodu31** [comment]
Wrong repo: https://github.com/flobz/psa_car_controller

**Comment by jove01** [comment]
Thank you for the answer
But i am on HA and I need the AddOn (I think!?)
<img width="355" alt="image" src="https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/assets/116289742/34f261b9-7627-4ac2-aa05-b3e4a469204c">

Than i get the Configuration above.

Where I am wrong?
