### ISSUE TITLE
[Feature Request] Control charge

### ISSUE THREAD

**Issue by flobz** [Flodu31/HomeAssistant-PeugeotIntegration#2]
Hello,
I add a documentation to describe how to do some stuff from Domoticz:
 - Change the charge threshold
 - Change stop hour
It can be useful to change these settings when you are planning a long trip.
Here is the link https://github.com/flobz/psa_car_controller/blob/master/docs/domoticz/Domoticz.md
If someone want to adapt it to Home Assistant it could be cool.

**Comment by Flodu31** [comment]
Thanks @flobz for the head up.
I will try to adapt the HA part soon with these 2 features.

**Comment by Flodu31** [comment]
Done :)
I added also the integration to activate clim and an automation to wake up every day at 6 AM :)
