### ISSUE TITLE
Add Peugeot 5008

### ISSUE THREAD

**Issue by wilwizard1979** [Flodu31/HomeAssistant-PeugeotIntegration#25]
Hi, sorry for reaching out via this media. I have a Peugeot 5008 Gasoline and would like to integrate in your library. I can contribute and will be happy to do it, so I will also learn. I'm a bit new on that, but I'm brave enough to do tge necessarybcoding and investigations. I just need some support yo start. Not sure how to contact you. Let me know please.

**Comment by Flodu31** [comment]
Hello,
Wrong repo => https://github.com/flobz/psa_car_controller
