### ISSUE TITLE
No data, controls fine

### ISSUE THREAD

**Issue by Freakandel74** [Flodu31/HomeAssistant-PeugeotIntegration#26]
Hi,

Thanks for your work at the PSA connector. I love the idea to control and manage my car (Opel GrandlandX hybrid4) from Home Assistant. 

I notice that the info in the card in Home Assistant is working fine, but the PSA Car Controller info is empty. I get always the 'No data to show, there is probably no trips recorded yet' notice. The switch to turn on the AC is working fine, also the mile indicator is working. So the API is getting data, but it seems to miss something.

**Comment by dreimer1986** [comment]
https://github.com/flobz/psa_car_controller Here you go. This has nothing to do with the HA integration for Flobz' Addon.
