### ISSUE TITLE
All data (trips, charge, ...) lost after upgrade to 3.0.8

### ISSUE THREAD

**Issue by nicknol** [Flodu31/HomeAssistant-PeugeotIntegration#28]
the other day I upgraded PSA Car Controller from version v3.0.7 to version v3.0.8.
And now all recorded data about trips, charges and so on have vanished.
I run PSA Car Controller on Raspberry PI4 with a Maria DB on a SSD.

How could I get my data back? I do full backups of HA each night, but restoring a backup would bring me back v3.0.7, and all changes since then to my HA would be lost

How could data loss be prevented in the future?

**Comment by Flodu31** [comment]
Wrong repo: https://github.com/flobz/psa_car_controller
