### ISSUE TITLE
e-208 json attributes

### ISSUE THREAD

**Issue by aleblack** [Flodu31/HomeAssistant-PeugeotIntegration#3]
Looks like that for e-208 the correct attributes in json response are: 

`value_template: '{{ states.sensor.peugeot_e208.attributes["energy"][0]["level"] }}'`
`value_template: '{{ states.sensor.peugeot_e208.attributes["energy"][0]["autonomy"] }}`
`value_template: '{{ states.sensor.peugeot_e208.attributes["energy"][0]["charging"]["status"] }}'`

**Comment by dreimer1986** [comment]
It jumpsed around from time to time. But for now you are right.

**Comment by Flodu31** [comment]
@dreimer1986 has right. Sometime it is 0, sometime 1.
I don’t know how we can fix this.

**Comment by flobz** [comment]
I can make a fix to always put the electric motor in first? What do you think?

**Comment by Flodu31** [comment]
If you can do that, it will be amazing, and we will not need to change the code when it changes
