### ISSUE TITLE
meaning of wakeup

### ISSUE THREAD

**Issue by Gabriele-tomai00** [Flodu31/HomeAssistant-PeugeotIntegration#32]
Is it necessary to wakeup car every morning? Can you explain what does it mean?
If I set a threshold, doesn't it always stay fixed until I go back to setting 100?
Thanks

**Comment by Flodu31** [comment]
I did it when I implemented the integration because I never had any updates, but you can try by disabling it.
Exactly. You will stay to the last setting, until you modify the threshold.
