### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by Doser86** [Flodu31/HomeAssistant-PeugeotIntegration#33]
How do I include the sensor.yaml?

I tried having all the sensors in configuration.yaml, but then only get errors.

**Comment by dreimer1986** [comment]
I have all of them in configuration.yaml and have no errors, so the problem seems to be your yaml.

But if you wanna split, add this at the beginning:

```
sensor: !include sensor.yaml
```

**Comment by Doser86** [comment]
The only thing I changed is vin and ip. The rest is just copied from your yaml.

**Comment by Flodu31** [comment]
Did you deployed this? https://github.com/flobz/psa_car_controller

**Comment by Doser86** [comment]
I have the PSA Car Controller running in HA

**Comment by Doser86** [comment]
When I have ewerything in configuration.yaml I get this:

bad indentation of a mapping entry (80:3)

 77 | 
 78 |        
 79 | # Peugeot e2008  
 80 |   - platform: rest
--------^
 81 |     name: peugeot_e2008
 82 |     resource: http://172.30.32.1: ...


Same goes for platfor: template

**Comment by dreimer1986** [comment]
And it explains you what you did wrong. Bad indentation. You can't just put stuff in a YAML. The indentation needs to be correct. Otherwise it will not be parsed correctly.

**Comment by Doser86** [comment]
I understand this is easy for people that understand coding.

I just copied your Yamls and changed like I said. I don't understand how to fix "bad indention" in this case.

**Comment by Flodu31** [comment]
https://www.yamllint.com/ validate your yaml file here
