### ISSUE TITLE
Config of AddOn

### ISSUE THREAD

**Issue by Gabriele-tomai00** [Flodu31/HomeAssistant-PeugeotIntegration#34]
Hi, where is the config of PSA in Home Assistant OS?
I need to change config like energy price and weather (using openweathermap key).
Thank

**Comment by Flodu31** [comment]
Hello,
You need to connect in SSH, and navigate to the folder.
Get the path to the volume:
```docker inspect -f '{{ .Mounts }}' $(docker ps -aqf "name=acc")```
In the folder you will have files you are looking for
Florent

**Comment by Gabriele-tomai00** [comment]
I have not Docker, I use HA in virtual machine. I don't find PSA in addons folder (it's empty).
I show you the folders:
![image](https://user-images.githubusercontent.com/69530000/217061310-8d72e305-a04b-4228-bd6c-016e7133f023.png)

**Comment by Gabriele-tomai00** [comment]
I have HA in a VM and PSA as addons from add-on store (I add it as add-on repositories).
So, when HA recognized it, I installed it as a normal add on.

**Comment by Flodu31** [comment]
Ok no idea so. I don't have this setup... Check on this repo: https://github.com/flobz/psa_car_controller

**Comment by Gabriele-tomai00** [comment]
ok thanks

**Comment by dreimer1986** [comment]
Add On Store IS Docker.

**Comment by Gabriele-tomai00** [comment]
so?

**Comment by Flodu31** [comment]
Follow what I said... connect with SSH, on port 22222

**Comment by dreimer1986** [comment]
I already saw that you made a issue over at flobz' repo. That was the best idea as here the repo is for the configuation.yaml editing you need to address the Add-On in HA and not much more tbh.
The parameters are not easily configurable when in a Docker.
- So they should be added to the configuration website IMO.
- Or the config must be located outside of the container.

https://github.com/flobz/psa_car_controller/issues/482 (just to link it ^^)

**Comment by Lahim26** [comment]
+1
I need to set the country code:
"ERROR :: Can't find country for None None"

**Comment by Ilpo55** [comment]
Hi.
In which file in the docker is the "energy price"?

**Comment by flobz** [comment]
@Flodu31 can you  give me the result of the command 'docker inspect -f '{{ .Mounts }}' $(docker ps -aqf "name=acc")'
please ? I will add a documentation for editing config file.

**Comment by Flodu31** [comment]
Hello,

Here it is:

```
[{bind  /dev /dev  ro false rprivate} {bind  /mnt/data/supervisor/addons/data/b9f12d83_psacc /data  rw true rprivate}]
```

**Comment by flobz** [comment]
and the result of  'ls /mnt/data/supervisor/addons/data/b9f12d83_psacc' ? :)

**Comment by Flodu31** [comment]
```
# ls /mnt/data/supervisor/addons/data/b9f12d83_psacc
activity.log                               info.db
activity.log.1                             info.db.bck
cars.json                                  info_backup_2021-07-02 18_39_17.715803.db
certs                                      mypeugeot.apk
charge_config.json                         options.json
config.ini                                 otp.bin
config.json
#
```

**Comment by flobz** [comment]
thanks for your help ! :)

**Comment by Ilpo55** [comment]
Why do I get "no such file or directory"?

```
➜  ~ docker inspect -f '{{ .Mounts }}' $(docker ps -aqf "name=acc") | grep -o '/mnt/data[^ ]*psacc'
/mnt/data/supervisor/addons/data/b9f12d83_psacc
➜  ~ cd /mnt/data/supervisor/addons/data/b9f12d83_psacc
cd: no such file or directory: /mnt/data/supervisor/addons/data/b9f12d83_psacc
➜  ~
```

**Comment by Ilpo55** [comment]
> Doc is done: https://github.com/flobz/psacc-ha/blob/main/psacc-ha/README.md#modify-config-file

Looks that this is not working with HA-addon (Home Assistant Generic x86-64).

**Comment by Alfagek** [comment]
Same problem over here as @Ilpo55 is saying. 
Working with the HA Addon. Using the SSH addon, showing working directory. But when you want to go to it, it doesn't exist.

Working with HA as a VM in Proxmox.

Anyother sollution to get to the files @flobz ?

**Comment by Ilpo55** [comment]
Before ssh disable **protection mode** in SSH & Web Terminal and restart it.

**Comment by Alfagek** [comment]
> Before ssh disable **protection mode** in SSH & Web Terminal and restart it.

did forgot that part (always running here ;-).

But its working for you @Ilpo55 ?

**Comment by Ilpo55** [comment]
>But its working for you @Ilpo55 ?

Yes, I have used it since Feb-22. Look at https://github.com/flobz/psa_car_controller/discussions/249#discussioncomment-5074356

:-)

**Comment by Alfagek** [comment]
> > But its working for you @Ilpo55 ?
> 
> Yes, I have used it since Feb-22. Look at [flobz/psa_car_controller#249 (reply in thread)](https://github.com/flobz/psa_car_controller/discussions/249#discussioncomment-5074356)
> 
> :-)
Damn, didn’t found that. It had saved me 45 minutes 🤣
