### ISSUE TITLE
Problems with the yaml und config-File

### ISSUE THREAD

**Issue by ifeelhorst** [Flodu31/HomeAssistant-PeugeotIntegration#36]
Hello @Flodu31 ,

sorry to bother you. Hope you can help me out. I tried to run through your configuration help but I have a few problems. I'm new to HA and maybe the problem sits in front of the PC (or in my case the Mac). 

### Two general questions:
I haven't yet a sensor.yaml but I included it
`sensor: !include sensor.yaml`
I think the code with "- id: '1617352487'" and so on must be in the "automations.yaml", correct?

### My main issue ..:
What should I do with the "customize.yaml". That file also didn't exist, but if I tried to check my configuration.yaml I get an error that the file didn't exist. I copied the whole string in the configuration.yaml but the the check break up with an unspecified error. 

### ..but maybe there is another main issue (missing config.file):
So I tried to start it – just to test the rest – without it. But I always get to errors:
ERROR :: No config file
WARNING :: Can't get language
INFO ::  * Running on http://0.0.0.0:5000/

So it seems for me that my basis configuration don't get the IP-Adress (from the sensor.yaml or configuration.yaml). Maybe that's the first problem I should solve (but don't know who important the customize.yaml is, so you get the whole story).

### Maybe it's interessting:
regardless of the error message, I tried to log into the gui with my user/pw-combination but get no response, too.

Thx a lot and ones again: sorry to bother you.
_Greetings Horst_

**Comment by Flodu31** [comment]
Hello,

You have right, id... must be placed in automations.yaml file.

Did you tried to browse the web page, with the IP of your HA + the port 5000?

Florent

**Comment by Duivelmolen** [comment]
> What should I do with the "customize.yaml". That file also didn't exist, but if I tried to check my configuration.yaml I get an error that the file didn't exist. I copied the whole string in the configuration.yaml but the the check break up with an unspecified error.

create a customize.yaml file

and put this in the configuration.yaml
homeassistant:
  customize: !include customize.yaml
