### ISSUE TITLE
Only able to load a few of the sensors, have copied and pasted to config and sensor.

### ISSUE THREAD

**Issue by boab21mac** [Flodu31/HomeAssistant-PeugeotIntegration#37]
Not sure why some load an other wont?![image](https://user-images.githubusercontent.com/120062210/221724274-84c5fb5b-92bf-4758-b62d-7fd93fab0d3c.png)

**Comment by ifeelhorst** [comment]
Maybe you could help me with my issue?
[(https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/issues/36)]

**Comment by Flodu31** [comment]
Hello,

Sorry for the delay, I was on holidays.

What is the name of your entities?

Florent

**Comment by Duivelmolen** [comment]
Hello,
Sorry I've got the same issue. 
I gave them an unique id. But that didn't help

  - platform: template
    sensors:
      e2008_battery_voltage:
        unique_id: 'e2008_battery_voltage'
        friendly_name: "Battery Voltage"

**Comment by Voz-DeCarabas** [comment]
I'm getting the same as boab21mac.  Setup was all fine and I have the PSA Car Controller dashboard and in that I can see the current battery charge level, the mileage and last charging session on the 'control' tab but nothing else is updating.  The map is saying I'm near Barcelona (I wish).  The other entities don't exist in HA.
My car is a e208 rather than an e2008.  I started with sensor.yaml and config yaml files with e2008 replaced with e208 and then realised e2008 might be hardcoded in the add on, so swapped it back, rebooted etc.  No difference. 
I tried going to http://IPofTheSoftware:5000/get_vehicleinfo/YourVIN?from_cache=1 in a browser (with the actual IP Address and the VIN for my car) and it says it's unreachable.

It feels like there's something obvious and I'm missing it.

**Comment by dreimer1986** [comment]
Not IPofTheSoftware... IPoftheHomeAssistant!
And don't forget this setting:
![image](https://user-images.githubusercontent.com/29841368/228913232-d5bdcbef-df85-457c-bdd9-9b8140517ca8.png)

**Comment by Voz-DeCarabas** [comment]
The software is on the home assistant so they are the same,  I just copied the line from the instructions. I also checked the port in the configuration and set it explicitly to 5000 and restarted.  No change. 
The entity for the switch for climate control works fine.
For the ‘summary’, ‘trips’ etc data is it only going to pick them up from this point onwards? Should I go for drive and see what happens?

**Comment by Voz-DeCarabas** [comment]
I aught to add a big thanks for this software.  The Peugeot software isn't as nice I would have hoped and so having a big button in HA view for pre-conditioning is great.

**Comment by Flodu31** [comment]
Hello,

If you can't browse the basic webpage, this integration will not work.

Florent

**Comment by Voz-DeCarabas** [comment]
I just checked again and I get a return with lots of lovely detail today and I can see it's plugged in, coordinates, mileage etc.  It's just not translating into things like correct map location on the 'PSA Car Controller' view and the additional entities like battery level don't exist in HA.  Actually, none of the sensors are created, just switches and the charge threshold input number and button.  I'll take another look at the sensor yaml.  I must have missed something

**Comment by Voz-DeCarabas** [comment]
and yes - I missed the include for sensor.yaml.  Plonker.  Let's see after a reboot.

**Comment by Voz-DeCarabas** [comment]
and to round this off (at least for me) several drives have meant that the statistics and location have started being reflected in the PSA Car Controller view, so all good.
Main learnings for me then
1) sensor.yaml needs to be an include in configuration.yaml if it's not already there (and you may need to create the sensor.yaml file as well),
2) some data elements may take time to be populated through using the car.  Be patient!
3) the examples are for an e2008. if your car is different, be careful with your renaming in the scripts if you want to rename and ensure you are consistant!

Thanks again for this add-on.

**Comment by boab21mac** [comment]
Just updated to the latest version of the PSA controller and I have lost a sensor 

![image](https://user-images.githubusercontent.com/120062210/231809600-914a6a00-d5ec-4ab6-b9e5-5218d27f11ad.jpeg)

Here is the code

        friendly_name: "Mileage"
        unit_of_measurement: "Miles"
        value_template: "{{ ((state_attr('sensor.peugeot_e2008', 'timed_odometer')['mileage']) / 1.609) | round(0)}}"

**Comment by Flodu31** [comment]
I have the same issue. The API is not returning the value (it is null)
We need to wait for an update

**Comment by Flodu31** [comment]
@boab21mac it is fixed with version 3.0.11 of the psa car controller app

**Comment by boab21mac** [comment]
Fixed now!!

**Comment by boab21mac** [comment]
Noticed people talking about the map data, is there a way to pull this out to HA?
