### ISSUE TITLE
Home Assistant Server

### ISSUE THREAD

**Issue by B4rtux** [Flodu31/HomeAssistant-PeugeotIntegration#4]
Bonjour Flo ! Tout d'abord merci, j'ai une question, je suis sûr Home Assistant sûr un Raspberry Pi 4, je n'arrive pas à trouver comment faire pour installer le PSA controller via python sûr Home Assistant (comme tu as pu le préciser dans ton Readme) , est ce que HA doit être sur une autre plateforme qu'un Raspberry ?..

Merci d'avance !

**Comment by Flodu31** [comment]
Hello,

Alors pour moi, le psa controller tourne sur un Pi dédié, du coup, je ne fais qu'appeler l'URL de ce dernier, en REST.

Apparemment c'est possible de le faire tourner sur un container maintenant, mais je n'ai pas testé.

En fait mon tuto ici, c'est pour ceux qui ont déjà le PSA controller qui tourne.

Florent

**Comment by B4rtux** [comment]
Ah mince ! Je débute encore la dedans x) , je repousserais "a demain" :') 

Merci bien ! 

Baptiste

**Comment by flobz** [comment]
Salut,
Tu peux suivre cette procédure pour l'installer en tant qu’add-on de home assistant.

**Comment by Flodu31** [comment]
Hello,
Merci c'est top.
Par contre, je démarre le service, et quand j'essaye d'acceder à l'UI, il me dit que le service n'est pas déployé, je le redémarre et ca refait pareil.
Florent

**Comment by flobz** [comment]
Tu peux le déinstaller et réessayer ? J'ai fait une correction il y a quelques minutes

**Comment by Flodu31** [comment]
Je l'ai fais, toujours rien. Page vide.

**Comment by Flodu31** [comment]
Containerised psa_car_controller loading...
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 8, in <module>
    import web.app
  File "/psa_car_controller/web/app.py", line 3, in <module>
    import dash_bootstrap_components as dbc
ModuleNotFoundError: No module named 'dash_bootstrap_components'

**Comment by B4rtux** [comment]
Pareil, moi le service ne veut pas démarrer du tout

**Comment by flobz** [comment]
Quelle est l'architecture du processeur du serveur ? C'est un raspberry?

**Comment by Flodu31** [comment]
Oui, Raspberry Pi 4

**Comment by flobz** [comment]
When this https://github.com/flobz/psa_car_controller/actions/runs/967369408 will be finished  can you retry please ? (uninstall and reinstall). it's was an arm64 architecture issue.

**Comment by Flodu31** [comment]
Same error, I removed the entire repo, add it again, and same issue:

```
Containerised psa_car_controller loading...
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 8, in <module>
    import web.app
  File "/psa_car_controller/web/app.py", line 3, in <module>
    import dash_bootstrap_components as dbc
ModuleNotFoundError: No module named 'dash_bootstrap_components'
```

**Comment by flobz** [comment]
et maintenant ?

**Comment by Flodu31** [comment]
Toujours la même erreur
