### ISSUE TITLE
IP? 

### ISSUE THREAD

**Issue by clarocha** [Flodu31/HomeAssistant-PeugeotIntegration#40]
Hi all, first I will like to thank all the developers for their work. I have a problem, The integration "PSA car controller" is working fine but I can't get the rest to work (control charging threshold, entities, etc.) I tried with the Home assistant IP and the IP of the PSA service, none working. What am I doing wrong?

Thanks
Claudio
![Captura de Ecrã (2)](https://user-images.githubusercontent.com/44841995/236180263-46a1f924-066b-44b1-bf36-ec4202e99ca2.png)

**Comment by Flodu31** [comment]
Hello

Did you followed this?

https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/blob/main/Citroen-ec4.md

Florent

**Comment by clarocha** [comment]
Hi Florent,

Yes, did, just didnt use the sensor.yaml, just put everything on configuration.yaml

Claudio

**Comment by Flodu31** [comment]
Ok strange, and do you have your sensors available?
Did you created automations too?
Florent

**Comment by clarocha** [comment]
No sensors available... Automations created! I´m not sure what IP I should add... Is it my Home assistant's IP address or the PSA instance address?
Claudio

**Comment by Flodu31** [comment]
It should be the IP of your home assistant.

**Comment by Flodu31** [comment]
I have no clue, it works for most of people, so I don't know where can be your issue if you followed the step by step

**Comment by dreimer1986** [comment]
Does your addon config look like this?

![image](https://user-images.githubusercontent.com/29841368/236229100-fe602833-a436-41af-98e2-1b4c348a950c.png)

**Comment by dreimer1986** [comment]
There is nothing attached ^^
