### ISSUE TITLE
Can this be used out of local wifi?

### ISSUE THREAD

**Issue by bgoncal** [Flodu31/HomeAssistant-PeugeotIntegration#42]
I live in an apartment, so my car stays far away from my home wifi, is it still possible to use it? (Peugeot e-208 2021 btw)

**Comment by nosuchuser** [comment]
Hi Bruno
Your car does not need access to any WiFi network for this integration to work. It has its own SIM card and data plan to communicate with the Stellantis servers and send/receive data.
The PSA Car Controller, on the other hand, will require access to the internet to interact with the Stellantis API and get/send data regarding your car. And you will need to be on the same network (by WiFi or some sort of remote access such as a VPN) of your running PSA Car Controller to interact with it.
