### ISSUE TITLE
in which yaml-file do I put???

### ISSUE THREAD

**Issue by hans19560** [Flodu31/HomeAssistant-PeugeotIntegration#52]
1. where do I put: - id: '1617352487' and so on
2. where do I put: type: entities and so on

**Comment by nosuchuser** [comment]
1. It can be "automations.yaml" but you can add them on the web UI (Settings->Automations->Create Automation)

2. You can add a new panel on a new or existing dashboard, edit and use "show code editor" in order to be able to paste raw yaml as its config
