### ISSUE TITLE
Peugeot e2008 facelift

### ISSUE THREAD

**Issue by Eduadel** [Flodu31/HomeAssistant-PeugeotIntegration#65]
Hello,

I recently acquired an Peugeot e2008 GT 115kW engine 54 kWh battery, facelift version that is generating a error on the log
"2024-01-18 09:17:40,929 :: WARNING :: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VR3UKZKWZP"

Regards

**Comment by Flodu31** [comment]
Hello,

Wrong repo: https://github.com/flobz/psa_car_controller
