### ISSUE TITLE
.

### ISSUE THREAD

**Issue by iendicott** [Flodu31/HomeAssistant-PeugeotIntegration#70]

**Comment by iendicott** [comment]
.

**Comment by dreimer1986** [comment]
And this has in which way something to do with the integration into HA you can find in this repo?!
Right, nothing at all.
Go there https://github.com/flobz/psa_car_controller

**Comment by iendicott** [comment]
Somone woke up on the wrong side of the bed. 
It was a simple question to which your response we particulary nasty. Well done!

**Comment by dreimer1986** [comment]
Nope it was not. It was stating a fact and nothing more. If you wanna see something as meant to be "nasty" you always can interpret text somehow to be that way of course.

**Comment by iendicott** [comment]
You seem like a very angry person with alot of anger issues. I have no time for people like you as you are a complete was a space and time.

#Keyboardwarrior
