### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by Cassiopea1** [Flodu31/HomeAssistant-PeugeotIntegration#8]
Hi,

after installation I've modified the sensor section with the resources:

`    http://192.168.1.130:5000/get_vehicleinfo/VR3xxxxxxxxxxxxxx?from_cache=1`
`    http://192.168.1.130:5000/charge_control?vin=VR3xxxxxxxxxxxxxx&?always_check=true`

but when I'm opening the web ui nothing happens and log reports:

`Containerised psa_car_controller loading...`
`/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: `
`The dash_html_components package is deprecated. Please replace`
`"import dash_html_components as html" with "from dash import html"`
`  import dash_html_components as html`
`2021-09-06 15:46:17,450 :: WARNING :: Can't get language`
`/psa_car_controller/web/views.py:7: UserWarning: `
`The dash_core_components package is deprecated. Please replace`
`"import dash_core_components as dcc" with "from dash import dcc"`
`  import dash_core_components as dcc`
`/psa_car_controller/web/figures.py:4: UserWarning: `
`The dash_table package is deprecated. Please replace`
`"import dash_table" with "from dash import dash_table"`
`Also, if you're using any of the table format helpers (e.g. Group), replace `
`"from dash_table.Format import Group" with `
`"from dash.dash_table.Format import Group"`
`  import dash_table`
`2021-09-06 15:46:21,304 :: INFO :: update_data`
` * Running on all addresses.`
`   WARNING: This is a development server. Do not use it in a production deployment.`
` * Running on http://172.30.33.5:5000/ (Press CTRL+C to quit)`
`172.30.32.1 - - [06/Sep/2021 15:47:57] "GET / HTTP/1.1" 200 -`
`172.30.32.1 - - [06/Sep/2021 15:47:57] "GET /assets/clientside.js HTTP/1.1" 304 -`
`172.30.32.1 - - [06/Sep/2021 15:47:59] "GET /_dash-layout HTTP/1.1" 200 -`
`172.30.32.1 - - [06/Sep/2021 15:47:59] "GET /_dash-dependencies HTTP/1.1" 200 -`

Is the "Running on http://172.30.33.5:5000/ " correct?
Any sugestions?

Thanks

**Comment by dreimer1986** [comment]
Yes and that's the IP your Docker Container has. Use that one for your REST sensors.

**Comment by Cassiopea1** [comment]
Where else should I use it?

**Comment by dreimer1986** [comment]
As typical for a IP, anywhere you wanna access the container and get data from the PSA API?!

**Comment by Cassiopea1** [comment]
My problem is that, when I click on PSA Car Controller in Home Assistant, I get briefly "Loading" and than an empty page. I believe that something must be displayed here.

![image](https://user-images.githubusercontent.com/84228832/132248886-e41d9232-9128-4cb0-8a2d-580257f74093.png)

**Comment by Flodu31** [comment]
Hello,
I can confirm that I have the same error, white page. it worked with the previous version.

```
2021-09-06 20:39:18,031 :: WARNING :: Can't get language
/psa_car_controller/web/views.py:7: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/psa_car_controller/web/figures.py:4: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`
Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table
```

Maybe @flobz can help us with this.

Thanks.
Florent

**Comment by dreimer1986** [comment]
Ah, now I understand what you are talking about. Yes, I have the same after updating. But as I do not use the website much I never noticed...

**Comment by Cassiopea1** [comment]
Biggest problem is that the configuration wizard does not start.

**Comment by dreimer1986** [comment]
That one should be your problem I guess. https://github.com/flobz/psa_car_controller/issues/217

**Comment by show2go** [comment]
Hello, I have the same problem, after updating Homeassistant System and PSA Car Controller

here is the log at startup:
Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-09-07 13:35:59,120 :: WARNING :: Can't get language
/psa_car_controller/web/views.py:7: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/psa_car_controller/web/figures.py:4: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`
Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table

Thanks for your help!

**Comment by dreimer1986** [comment]
Well, before ppl start to fill @Flodu31 's Issues page now. Both are no problems of THIS collection of how to nicely integrate the addin into HA. That's why I posted the report in the repo you should report the problems to. ^^

**Comment by Cassiopea1** [comment]
@dreimer1986   Nice. A link to the "should report repo" would be helpful for ppl for future "problems".
Do you know if there is a forum or a discord channel where people are discussing over PSA Car Controller?

**Comment by show2go** [comment]
Oh, i didnt realize that i am in the wrong repo...
thx for the hint!
